feat: support python 3.13
pypa/readme_renderer pull request #319
Opened 2024-10-14 10:55 UTC by shenxianpeng

Since Python 3.13 was officially released on October 7, 2024. Do you need to support it?

2024-10-15 14:48 UTC, miketheman requested changes
Thanks - one minor change, but otherwise good to go.

2024-10-15 14:48 UTC, miketheman commented on .gitpod.yml
> +      export PY_VERSIONS="3.8 3.9 3.10 3.11 3.12 3.13"
Support for 3.8 dropped in #315 this is a leftover
```suggestion
      export PY_VERSIONS="3.9 3.10 3.11 3.12 3.13"
```

2024-10-15 14:48 UTC, miketheman approved these changes

2024-11-13 07:14 UTC, Karinza38 commented
shenxianpeng:support-py313

2024-11-13 14:14 UTC, merged